# Generated by Django 2.1.5 on 2019-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
